In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv('Laptop.csv')
df.head()

,Number,Brand,Model,Series,Processor,Processor_Gen,RAM,Hard_Disk_Capacity,OS,Rating,Price
0,0,DELL,Inspiron,NaN,i3,11th,8.0,1 TB HDD,Windows 11 Home,3.7,39040
1,1,DELL,Vostro,NaN,i5,11th,8.0,1 TB HDD,Windows 10 Home,3.6,50840
2,2,ASUS,VivoBook,15,i3,10th,8.0,512 GB SSD,Windows 11 Home,4.3,37940
3,3,DELL,Inspiron,NaN,i3,11th,8.0,1 TB HDD,256 GB SSD,4.4,44440
4,4,ASUS,TUF,Gaming,i5,10th,8.0,512 GB SSD,Windows 10 Home,4.5,57940

In [3]:
print(df.shape)

(130, 11)

In [4]:
df.isnull().sum()

Number                 0
Brand                  0
Model                 14
Series                50
Processor              7
Processor_Gen          7
RAM                    8
Hard_Disk_Capacity     8
OS                     8
Rating                 0
Price                  0
dtype: int64

In [6]:
df.duplicated().sum()

0

In [7]:
df.groupby('Model').count()['Rating']

Model
15q            1
2020           4
250-G6         1
3000           1
APU            1
ASUS           1
Aspire         1
Book           1
Chromebook     2
Envy           1
GF63           1
HP             2
IDEAPAD        1
IdeaPad       15
Ideapad        6
Inspiron      26
Katana         1
MacBook        3
Nitro          1
Notebook       1
Pavilion       3
ROG            2
Ryzen          5
Surface        1
Swift          1
TUF            2
Thinkpad       1
Travelmate     1
VivoBook      11
Vivobook       6
Vostro        10
ZenBook        1
v15            1
Name: Rating, dtype: int64

In [15]:
num_rating_df=df.groupby('Model').count()['Rating'].reset_index()
num_rating_df.rename(columns={'Ratings':'num_ratings'},inplace=True)
num_rating_df

         Model  Rating
0          15q       1
1         2020       4
2       250-G6       1
3         3000       1
4          APU       1
5         ASUS       1
6       Aspire       1
7         Book       1
8   Chromebook       2
9         Envy       1
10        GF63       1
11          HP       2
12     IDEAPAD       1
13     IdeaPad      15
14     Ideapad       6
15    Inspiron      26
16      Katana       1
17     MacBook       3
18       Nitro       1
19    Notebook       1
20    Pavilion       3
21         ROG       2
22       Ryzen       5
23     Surface       1
24       Swift       1
25         TUF       2
26    Thinkpad       1
27  Travelmate       1
28    VivoBook      11
29    Vivobook       6
30      Vostro      10
31     ZenBook       1
32         v15       1

In [16]:
avg_ratings_df=df.groupby('Model').mean().reset_index()
avg_ratings_df.rename(columns={'Ratings':'avg_ratings'},inplace=True)
avg_ratings_df

         Model      Number        RAM    Rating          Price
0          15q  126.000000   4.000000  4.200000   32905.000000
1         2020   77.500000        NaN  4.650000  113965.000000
2       250-G6  119.000000   4.000000  4.200000   46150.000000
3         3000  117.000000   8.000000  4.200000   43850.000000
4          APU  116.000000   4.000000  3.900000   21846.000000
5         ASUS   61.000000   8.000000  4.500000   71940.000000
6       Aspire   16.000000   8.000000  4.400000   52940.000000
7         Book   67.000000   8.000000  4.400000   46940.000000
8   Chromebook  103.500000   4.000000  3.900000   20565.000000
9         Envy  105.000000   8.000000  4.300000   74940.000000
10        GF63   47.000000   8.000000  4.500000   65940.000000
11          HP   85.000000  12.000000  4.450000   65940.000000
12     IDEAPAD  109.000000   8.000000  3.700000   59850.000000
13     IdeaPad   57.866667   8.533333  4.313333   45873.333333
14     Ideapad   74.500000  10.666667  4.383333   60276.333333
15    Inspiron   57.807692   8.769231  4.015385   46033.461538
16      Katana   68.000000  16.000000  4.400000   76940.000000
17     MacBook   92.000000        NaN  4.500000  115273.333333
18       Nitro   59.000000   8.000000  4.500000   72940.000000
19    Notebook   85.000000   8.000000  3.900000   40940.000000
20    Pavilion   67.666667  13.333333  4.466667   78006.666667
21         ROG   78.500000   8.000000  4.600000   74440.000000
22       Ryzen   44.200000   8.000000  4.380000   43300.000000
23     Surface  102.000000   8.000000  4.500000   91949.000000
24       Swift  106.000000   8.000000  4.600000   59940.000000
25         TUF   35.000000  12.000000  4.550000   73940.000000
26    Thinkpad   19.000000   8.000000  4.100000   57440.000000
27  Travelmate  122.000000  16.000000  3.400000   62440.000000
28    VivoBook   40.272727   8.727273  4.309091   46485.454545
29    Vivobook   82.500000   7.333333  3.933333   41225.000000
30      Vostro   58.000000   7.555556  3.910000   45448.600000
31     ZenBook  110.000000  16.000000  4.400000  114940.000000
32         v15  127.000000   4.000000  3.100000   39949.000000

In [17]:
popular_df=num_rating_df.merge(avg_ratings_df,on='Model')
popular_df

         Model  Rating_x      Number        RAM  Rating_y          Price
0          15q         1  126.000000   4.000000  4.200000   32905.000000
1         2020         4   77.500000        NaN  4.650000  113965.000000
2       250-G6         1  119.000000   4.000000  4.200000   46150.000000
3         3000         1  117.000000   8.000000  4.200000   43850.000000
4          APU         1  116.000000   4.000000  3.900000   21846.000000
5         ASUS         1   61.000000   8.000000  4.500000   71940.000000
6       Aspire         1   16.000000   8.000000  4.400000   52940.000000
7         Book         1   67.000000   8.000000  4.400000   46940.000000
8   Chromebook         2  103.500000   4.000000  3.900000   20565.000000
9         Envy         1  105.000000   8.000000  4.300000   74940.000000
10        GF63         1   47.000000   8.000000  4.500000   65940.000000
11          HP         2   85.000000  12.000000  4.450000   65940.000000
12     IDEAPAD         1  109.000000   8.000000  3.700000   59850.000000
13     IdeaPad        15   57.866667   8.533333  4.313333   45873.333333
14     Ideapad         6   74.500000  10.666667  4.383333   60276.333333
15    Inspiron        26   57.807692   8.769231  4.015385   46033.461538
16      Katana         1   68.000000  16.000000  4.400000   76940.000000
17     MacBook         3   92.000000        NaN  4.500000  115273.333333
18       Nitro         1   59.000000   8.000000  4.500000   72940.000000
19    Notebook         1   85.000000   8.000000  3.900000   40940.000000
20    Pavilion         3   67.666667  13.333333  4.466667   78006.666667
21         ROG         2   78.500000   8.000000  4.600000   74440.000000
22       Ryzen         5   44.200000   8.000000  4.380000   43300.000000
23     Surface         1  102.000000   8.000000  4.500000   91949.000000
24       Swift         1  106.000000   8.000000  4.600000   59940.000000
25         TUF         2   35.000000  12.000000  4.550000   73940.000000
26    Thinkpad         1   19.000000   8.000000  4.100000   57440.000000
27  Travelmate         1  122.000000  16.000000  3.400000   62440.000000
28    VivoBook        11   40.272727   8.727273  4.309091   46485.454545
29    Vivobook         6   82.500000   7.333333  3.933333   41225.000000
30      Vostro        10   58.000000   7.555556  3.910000   45448.600000
31     ZenBook         1  110.000000  16.000000  4.400000  114940.000000
32         v15         1  127.000000   4.000000  3.100000   39949.000000

In [19]:
popular_df=popular_df.drop('Number',axis=1)
popular_df

         Model  Rating_x        RAM  Rating_y          Price
0          15q         1   4.000000  4.200000   32905.000000
1         2020         4        NaN  4.650000  113965.000000
2       250-G6         1   4.000000  4.200000   46150.000000
3         3000         1   8.000000  4.200000   43850.000000
4          APU         1   4.000000  3.900000   21846.000000
5         ASUS         1   8.000000  4.500000   71940.000000
6       Aspire         1   8.000000  4.400000   52940.000000
7         Book         1   8.000000  4.400000   46940.000000
8   Chromebook         2   4.000000  3.900000   20565.000000
9         Envy         1   8.000000  4.300000   74940.000000
10        GF63         1   8.000000  4.500000   65940.000000
11          HP         2  12.000000  4.450000   65940.000000
12     IDEAPAD         1   8.000000  3.700000   59850.000000
13     IdeaPad        15   8.533333  4.313333   45873.333333
14     Ideapad         6  10.666667  4.383333   60276.333333
15    Inspiron        26   8.769231  4.015385   46033.461538
16      Katana         1  16.000000  4.400000   76940.000000
17     MacBook         3        NaN  4.500000  115273.333333
18       Nitro         1   8.000000  4.500000   72940.000000
19    Notebook         1   8.000000  3.900000   40940.000000
20    Pavilion         3  13.333333  4.466667   78006.666667
21         ROG         2   8.000000  4.600000   74440.000000
22       Ryzen         5   8.000000  4.380000   43300.000000
23     Surface         1   8.000000  4.500000   91949.000000
24       Swift         1   8.000000  4.600000   59940.000000
25         TUF         2  12.000000  4.550000   73940.000000
26    Thinkpad         1   8.000000  4.100000   57440.000000
27  Travelmate         1  16.000000  3.400000   62440.000000
28    VivoBook        11   8.727273  4.309091   46485.454545
29    Vivobook         6   7.333333  3.933333   41225.000000
30      Vostro        10   7.555556  3.910000   45448.600000
31     ZenBook         1  16.000000  4.400000  114940.000000
32         v15         1   4.000000  3.100000   39949.000000

In [20]:
popular_df=popular_df.drop('RAM',axis=1)
popular_df

         Model  Rating_x  Rating_y          Price
0          15q         1  4.200000   32905.000000
1         2020         4  4.650000  113965.000000
2       250-G6         1  4.200000   46150.000000
3         3000         1  4.200000   43850.000000
4          APU         1  3.900000   21846.000000
5         ASUS         1  4.500000   71940.000000
6       Aspire         1  4.400000   52940.000000
7         Book         1  4.400000   46940.000000
8   Chromebook         2  3.900000   20565.000000
9         Envy         1  4.300000   74940.000000
10        GF63         1  4.500000   65940.000000
11          HP         2  4.450000   65940.000000
12     IDEAPAD         1  3.700000   59850.000000
13     IdeaPad        15  4.313333   45873.333333
14     Ideapad         6  4.383333   60276.333333
15    Inspiron        26  4.015385   46033.461538
16      Katana         1  4.400000   76940.000000
17     MacBook         3  4.500000  115273.333333
18       Nitro         1  4.500000   72940.000000
19    Notebook         1  3.900000   40940.000000
20    Pavilion         3  4.466667   78006.666667
21         ROG         2  4.600000   74440.000000
22       Ryzen         5  4.380000   43300.000000
23     Surface         1  4.500000   91949.000000
24       Swift         1  4.600000   59940.000000
25         TUF         2  4.550000   73940.000000
26    Thinkpad         1  4.100000   57440.000000
27  Travelmate         1  3.400000   62440.000000
28    VivoBook        11  4.309091   46485.454545
29    Vivobook         6  3.933333   41225.000000
30      Vostro        10  3.910000   45448.600000
31     ZenBook         1  4.400000  114940.000000
32         v15         1  3.100000   39949.000000

In [21]:
popular_df=popular_df.drop('Price',axis=1)
popular_df

         Model  Rating_x  Rating_y
0          15q         1  4.200000
1         2020         4  4.650000
2       250-G6         1  4.200000
3         3000         1  4.200000
4          APU         1  3.900000
5         ASUS         1  4.500000
6       Aspire         1  4.400000
7         Book         1  4.400000
8   Chromebook         2  3.900000
9         Envy         1  4.300000
10        GF63         1  4.500000
11          HP         2  4.450000
12     IDEAPAD         1  3.700000
13     IdeaPad        15  4.313333
14     Ideapad         6  4.383333
15    Inspiron        26  4.015385
16      Katana         1  4.400000
17     MacBook         3  4.500000
18       Nitro         1  4.500000
19    Notebook         1  3.900000
20    Pavilion         3  4.466667
21         ROG         2  4.600000
22       Ryzen         5  4.380000
23     Surface         1  4.500000
24       Swift         1  4.600000
25         TUF         2  4.550000
26    Thinkpad         1  4.100000
27  Travelmate         1  3.400000
28    VivoBook        11  4.309091
29    Vivobook         6  3.933333
30      Vostro        10  3.910000
31     ZenBook         1  4.400000
32         v15         1  3.100000

In [25]:
popular_df[popular_df['Rating_y']>=3.1].sort_values('Rating_x',ascending=False).head(20)

         Model  Rating_x  Rating_y
15    Inspiron        26  4.015385
13     IdeaPad        15  4.313333
28    VivoBook        11  4.309091
30      Vostro        10  3.910000
14     Ideapad         6  4.383333
29    Vivobook         6  3.933333
22       Ryzen         5  4.380000
1         2020         4  4.650000
17     MacBook         3  4.500000
20    Pavilion         3  4.466667
21         ROG         2  4.600000
8   Chromebook         2  3.900000
25         TUF         2  4.550000
11          HP         2  4.450000
0          15q         1  4.200000
23     Surface         1  4.500000
26    Thinkpad         1  4.100000
27  Travelmate         1  3.400000
31     ZenBook         1  4.400000
24       Swift         1  4.600000

In [28]:
popular_df=popular_df[popular_df['Rating_y']>=3.1].sort_values('Rating_x',ascending=False).head(20)
popular_df

         Model  Rating_x  Rating_y
15    Inspiron        26  4.015385
13     IdeaPad        15  4.313333
28    VivoBook        11  4.309091
30      Vostro        10  3.910000
14     Ideapad         6  4.383333
29    Vivobook         6  3.933333
22       Ryzen         5  4.380000
1         2020         4  4.650000
17     MacBook         3  4.500000
20    Pavilion         3  4.466667
25         TUF         2  4.550000
11          HP         2  4.450000
21         ROG         2  4.600000
8   Chromebook         2  3.900000
0          15q         1  4.200000
23     Surface         1  4.500000
26    Thinkpad         1  4.100000
27  Travelmate         1  3.400000
31     ZenBook         1  4.400000
24       Swift         1  4.600000

In [29]:
book=pd.read_csv('book.csv')

In [30]:
popular_df.merge(book,on='Model')

          Model  Rating_x  Rating_y      Brand Processor   RAM
0      Inspiron        26  4.015385       DELL        i3   8.0
1      Inspiron        26  4.015385       DELL        i3   8.0
2      Inspiron        26  4.015385       DELL     3050U   4.0
3      Inspiron        26  4.015385       DELL        i5  16.0
4      Inspiron        26  4.015385       DELL     3250U   8.0
..          ...       ...       ...        ...       ...   ...
98      Surface         1  4.500000  MICROSOFT        i5   8.0
99     Thinkpad         1  4.100000     Lenovo     5600U   8.0
100  Travelmate         1  3.400000       acer        i5  16.0
101     ZenBook         1  4.400000       ASUS        i5  16.0
102       Swift         1  4.600000       acer        i5   8.0

[103 rows x 6 columns]

In [35]:
popular_df.merge(book,on='Model').drop_duplicates('Model')

          Model  Rating_x  Rating_y      Brand Processor   RAM
0      Inspiron        26  4.015385       DELL        i3   8.0
26      IdeaPad        15  4.313333     Lenovo        i3   8.0
41     VivoBook        11  4.309091       ASUS        i3   8.0
52       Vostro        10  3.910000       DELL        i5   8.0
62      Ideapad         6  4.383333     Lenovo        i5  16.0
68     Vivobook         6  3.933333       ASUS        i3   8.0
74        Ryzen         5  4.380000       ASUS     3250U   8.0
79         2020         4  4.650000      APPLE       NaN   NaN
83      MacBook         3  4.500000      APPLE       NaN   NaN
86     Pavilion         3  4.466667         HP     5600H   8.0
89          TUF         2  4.550000       ASUS        i5   8.0
91           HP         2  4.450000         HP     4600H   8.0
93          ROG         2  4.600000       ASUS    4800HS   8.0
95   Chromebook         2  3.900000       ASUS         -   4.0
97          15q         1  4.200000         HP        i3   4.0
98      Surface         1  4.500000  MICROSOFT        i5   8.0
99     Thinkpad         1  4.100000     Lenovo     5600U   8.0
100  Travelmate         1  3.400000       acer        i5  16.0
101     ZenBook         1  4.400000       ASUS        i5  16.0
102       Swift         1  4.600000       acer        i5   8.0

In [37]:
popular_df=popular_df.merge(book,on='Model').drop_duplicates('Model')
popular_df

,Model,Rating_x,Rating_y,Brand_x,Processor_x,RAM_x,Brand_y,Processor_y,RAM_y
0,Inspiron,26,4.015385,DELL,i3,8.0,DELL,i3,8.0
26,IdeaPad,15,4.313333,Lenovo,i3,8.0,Lenovo,i3,8.0
41,VivoBook,11,4.309091,ASUS,i3,8.0,ASUS,i3,8.0
52,Vostro,10,3.910000,DELL,i5,8.0,DELL,i5,8.0
62,Ideapad,6,4.383333,Lenovo,i5,16.0,Lenovo,i5,16.0
68,Vivobook,6,3.933333,ASUS,i3,8.0,ASUS,i3,8.0
74,Ryzen,5,4.380000,ASUS,3250U,8.0,ASUS,3250U,8.0
79,2020,4,4.650000,APPLE,NaN,NaN,APPLE,NaN,NaN
83,MacBook,3,4.500000,APPLE,NaN,NaN,APPLE,NaN,NaN
86,Pavilion,3,4.466667,HP,5600H,8.0,HP,5600H,8.0
89,TUF,2,4.550000,ASUS,i5,8.0,ASUS,i5,8.0
91,HP,2,4.450000,HP,4600H,8.0,HP,4600H,8.0
93,ROG,2,4.600000,ASUS,4800HS,8.0,ASUS,4800HS,8.0
95,Chromebook,2,3.900000,ASUS,-,4.0,ASUS,-,4.0
97,15q,1,4.200000,HP,i3,4.0,HP,i3,4.0
98,Surface,1,4.500000,MICROSOFT,i5,8.0,MICROSOFT,i5,8.0
99,Thinkpad,1,4.100000,Lenovo,5600U,8.0,Lenovo,5600U,8.0
100,Travelmate,1,3.400000,acer,i5,16.0,acer,i5,16.0
101,ZenBook,1,4.400000,ASUS,i5,16.0,ASUS,i5,16.0
102,Swift,1,4.600000,acer,i5,8.0,acer,i5,8.0